### PR TITLE
check to verify if bump2version is installed

### PR DESCRIPTION
**Pull request by ravikamaraj**
@wslulciuc 
I have indented the new code with 2 spaces. Kindly let me know or point to any specific format that is followed across the project. thanks!

### CODE REVIEW

**Comment by wslulciuc** [comment]
>  Kindly let me know or point to any specific format that is followed across the project.

We follow google's style guide: https://google.github.io/styleguide/shell.xml

**Review by wslulciuc — COMMENTED** [review]
Code looks great, @ravikamaraj! I have two minor suggestions:

1. I would verify `bump2version` is installed before ensuring the script is run against the `master` branch.
2. For simplicity, I would in-line the verification of `bump2version`. I think wrapping the verification in a function call does provide a nice one-line step, but given the function is not reused, it's okay to in-line the code outside a function.

**Comment by ravikamaraj** [comment]
@wslulciuc, updated the code per your review suggestions. thanks!

**Review by wslulciuc — APPROVED** [review]
@ravikamaraj 👍

**Pull request merged**
