### PR TITLE
Fix path generation for http backend

### PR DESCRIPTION
**Pull request by wslulciuc**

### CODE REVIEW

**Comment by wslulciuc** [comment]
Where I added the '/' may not be were the issue is, might be here https://github.com/MarquezProject/marquez-python/blob/main/marquez_client/client_wo.py#L200. Need to explore more where the root cause might be.

**Comment by julienledem** [comment]
I was wondering if the renaming of the `_url` function here is not the cause:
def **path**(self, **path**, *args): 
both the function and the param are named the same
https://github.com/DatakinHQ/marquez-python/commit/ce5b9d764ff2d9b73f26eddd52b337d9a86f24cb#diff-61472eed31801c3aeeac9d1ca43c8ff0R197

**Comment by wslulciuc** [comment]
@julienledem Yep, that's certainly, and most likely, the issue.

**Comment by julienledem** [comment]
could you add a unit test for the `_path` method?
since it's static, it can be tested independently.

**Review by julienledem — APPROVED** [review]
Thank you!

**Pull request merged**
